### PR TITLE
Update to NS v8

### PR DESCRIPTION
**Pull request by joshmossas**
This pull request makes several changes to get `nativescript-vue-devtools` working with **Nativescript v8.0.1** and **@vue/devtools v5.x.x** (These changes **do not** work with **@vue/devtools v6.x.x-beta**)

## Changes for NS 8:

- `nativescript-toasty` replaced with `@triniwiz/nativescript-toasty`
- `nativescript-socketio` replaced with `@triniwiz/nativescript-socketio`

## Additional Quality of Life Changes:

- The toasty and socketio plugins removed from "peerDependencies" and added to "dependencies" reducing the need for additional package installations (`@nativescript/core`, `@vue/devtools`, and `vue` are still listed as peerDependencies, but two of those three would get installed anyway when creating a Nativescript Vue app)
- Migrated to typescript

### CODE REVIEW

**Comment by rigor789** [comment]
Wow! Thanks! 

The only reason I kept toasty and socketio as peerDependencies is that a project could be already using those, and if there are different versions of the same plugin - the build would likely fail due to duplicate symbols/classes. But by using the caret range, it should generally resolve to the same version a project may already be using. In the other cases (ie a major bump in one of the plugins), we'll need to publish an update as well.

**Comment by joshmossas** [comment]
@rigor789 
Oh I gotcha that makes sense. I'll swap them back to peer dependencies.

**Comment by joshmossas** [comment]
Okay the toasty and socketio plugins have been moved  back to Peer Dependencies. Also you'll noticed that the peer dependencies are also listed as dev dependencies. This is so that typescript can resolve the types when compiling.

Let me know if there are any other changes needed

**Comment by rigor789** [comment]
LGTM! Thanks - I'll get this merged & released soon (hopefully today, but if I miss that, please do ping me - I keep jumping between too many different projects/packages and sometimes forget)

**Comment by joshmossas** [comment]
No worries. I totally understand.

I made one additional change which is setting `module` in the tsconfig.json to `CommonJS`. I noticed this line in the v7 docs and figured I should change it just to be safe.

image

I've already tried both the CommonJS and ES2015 variant in my project (Vue + Typescript) and they both work. However I suspect CommonJS will be better for vanilla JS projects.

**Comment by rigor789** [comment]
Should be fine as ES2015 since all apps are built with Webpack now - so that line in the old docs doesn't directly apply (the runtime itself is using commonjs, and webpack outputs commonjs).
